### ISSUE TITLE
Disappearing generators

### ISSUE THREAD

**Issue by BonezTheWonderful** [StickyPiston-development/CreateCobblestone#12] opened 2024-07-27 09:46 UTC
Attempted to make a deepslate generator 
Tried manual and automatic 
Both resulted in the block being destroyed
I checked and had both Deepslate and Cobbled deepslate enabled.

**Comment by MrStickyPiston** [comment] 2024-07-27 15:28
Did you restart?

**Comment by BonezTheWonderful** [comment] 2024-07-29 07:06
> Did you restart?

yup still just *POP*

**Comment by MrStickyPiston** [comment] 2024-07-29 07:13
Could you provide logs?

**Comment by BonezTheWonderful** [comment] 2024-07-29 08:25
[latest.log](https://github.com/user-attachments/files/16409712/latest.log)

**Comment by MrStickyPiston** [comment] 2024-07-29 08:29
Why did you close the issue?

**Comment by BonezTheWonderful** [comment] 2024-07-29 23:23
hit it by accident my bad

**Comment by MrStickyPiston** [comment] 2024-07-31 07:22
Can you send the config file? (Search 'cobblestone' in the config folder. It looks like something is wrong with your config.

**Comment by BonezTheWonderful** [comment] 2024-07-31 20:46
[createcobblestone-common.zip](https://github.com/user-attachments/files/16447042/createcobblestone-common.zip)
had to copmress it

**Comment by MrStickyPiston** [comment] 2024-08-01 06:42
Can you try it again and send logs again? The config looks fine.

**Comment by BonezTheWonderful** [comment] 2024-08-01 20:43
[latest.log](https://github.com/user-attachments/files/16461757/latest.log)
I also noticed this time that the generators don't appear in the creative search menu

**Comment by MrStickyPiston** [comment] 2024-08-02 07:07
The log no longer says something about the config, can you send it again?

**Comment by MrStickyPiston** [comment] 2024-08-02 07:30
Btw do they appear as /give or as blocks usin /setblock

**Comment by BonezTheWonderful** [comment] 2024-08-02 22:44
No to both of those the config says that they are enabled but the game acts like they don't exist 
[latest.log](https://github.com/user-attachments/files/16475909/latest.log)
most recent log

**Comment by MrStickyPiston** [comment] 2024-08-04 11:48
So also no blocks? Can you try disabling some other mods?

**Comment by BonezTheWonderful** [comment] 2024-08-08 07:16
Yea i tried that a while ago still nothing

**Comment by MrStickyPiston** [comment] 2024-08-08 07:37
Marked it as bug, but i could not reproduce it

**Comment by MrStickyPiston** [comment] 2024-08-20 15:40
i could reproduce it today, it seems to be forge specefic.

**Comment by MrStickyPiston** [comment] 2024-08-25 07:26
I found the problem: the forge config system is not loaded when the blocks are added, so the default values are added. I dont know a fix yet.

**Comment by BonezTheWonderful** [comment] 2024-09-04 00:02
Damn hopefully you can i'll use an alternative but this mod already has a place in my heart

**Comment by TrizzlyGH** [comment] 2024-09-04 00:04
perhaps changing the default values might be an easy fix for us users at the moment until an update comes out.

**Comment by MrStickyPiston** [comment] 2024-09-04 06:23
> perhaps changing the default values might be an easy fix for us users at the moment until an update comes out.

Might do this just for you guys, but i cant release that on modrinth or curseforge because it is not really vanilla create

**Comment by TrizzlyGH** [comment] 2024-09-04 13:24
Perhaps a tutorial so that we could do it ourselves? Maybe if you have a discord server you could post the fix there along with the problems that are occuring as to why the config isn't affecting the CreateCobblestoneCommon.class (?)

**Comment by MrStickyPiston** [comment] 2024-09-04 15:06
it was not much work, here it is: https://github.com/StickyPiston-development/CreateCobblestone/actions/runs/10703195463
It requires a github account to download.

**Comment by MrStickyPiston** [comment] 2024-09-04 15:07
WARNING: this was not the real fix, the issue remains open

**Comment by MrStickyPiston** [comment] 2024-09-15 16:38
@TrizzlyGH , @BonezTheWonderful 

I rewrote the biggest part of the mod and i think i fixed it. Please try out the new test build below IN A TEST WORLD. All old generators will be wiped.

https://github.com/StickyPiston-development/CreateCobblestone/actions/runs/10872396524

**Comment by MrStickyPiston** [comment] 2024-09-15 16:49
Known issues: items dont have the block they generate on them and the lighting is weird for the block.

**Comment by MrStickyPiston** [comment] 2024-09-16 12:25
New version: https://github.com/StickyPiston-development/CreateCobblestone/actions/runs/10883360759

Fixed lighting

**Comment by MrStickyPiston** [comment] 2024-09-18 11:25
Fixed in the latest beta on modrinth and curseforge

**Closed as completed** 2024-09-18 11:28 UTC
Labels: bug
